uploads = []
generated = []

[[outputs]]
id = "D6Wxu6lg009T4SemlFuxK"
uri = "file://cremosoburguer.tar.gz"
type = "unspecified"
title = "cremosoburguer.tar.gz — Backup atualizado"

[[outputs]]
id = "RIEnFey0sJ2Qo8ATAbp16"
uri = "file://novos_arquivos_repo.tar.gz"
type = "unspecified"
title = "Arquivos novos do repositório + Relatório"

[[outputs]]
id = "xJ8ExlLO944N1R8MuL5D8"
uri = "file://auditoria-persistencia.md"
type = "text"
title = "Auditoria de Persistência — Cremoso Burguer"

[[outputs]]
id = "fu5qOFUyYuM6KlgELUs4P"
uri = "file://relatorio-auditoria.md"
type = "text"
title = "Relatório de Auditoria Técnica — Cremoso Burguer"
